fix: run script

diff --git a/.devops/soak-tests-pipeline.yml b/.devops/soak-tests-pipeline.yml
--- a/.devops/soak-tests-pipeline.yml
+++ b/.devops/soak-tests-pipeline.yml
@@ -146,11 +146,23 @@ jobs:
                 
                 PY_SCRIPT=./src/generateImportFile_${{ parameters.FILE_TYPE }}.py
                 chmod +x $PY_SCRIPT
-                FILE_TO_UPLOAD=`python3 -m pipenv run $PY_SCRIPT ${{ variables.FILE_VERSION }} ${{ parameters.N_ROWS }}`
+                FILE_TO_UPLOAD=`python3 -m pipenv run python $PY_SCRIPT ${{ variables.FILE_VERSION }} ${{ parameters.N_ROWS }}`
+                if [[ -z "${DEPLOY_ENV}" ]]; then
+                  echo "Cannot generate file to upload!"
+                  exit 1
+                fi
+                echo "Generated file to upload: $FILE_TO_UPLOAD"
                 
                 IMPORT_RESPONSE=`curl -s --location --globoff '${{ variables.BASE_URL }}/pu/fileshare/organization/$ORGANIZATION_ID/ingestionflowfiles?ingestionFlowFileType=${{ parameters.FILE_TYPE }}&fileOrigin=SIL' \
                   --header 'Authorization: Bearer $ACCESS_TOKEN' \
                     --form "ingestionFlowFile=@\"./$FILE_TO_UPLOAD\""`
+                if [[ -z "${IMPORT_RESPONSE}" ]]; then
+                  echo "No body returned from upload invoke!"
+                  exit 1
+                else
+                  echo "Import response: $IMPORT_RESPONSE"
+                fi
+                
                 INGESTION_FLOW_FILE_ID=$(echo IMPORT_RESPONSE | jq .ingestionFlowFileId)
                 
                 echo Imported ${{ parameters.FILE_TYPE }} with ingestionFlowFileId $INGESTION_FLOW_FILE_ID
